# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('emailaddr', models.CharField(max_length=100)),
                ('phonenum', models.CharField(max_length=11)),
                ('date_of_birth', models.DateField()),
                ('height', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CreateUser',
        ),
    ]
