# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipear', '0003_auto_20170502_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
